name: Type and Lint checks

on:
  pull_request:
    branches:
      - main

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Install mypy
        run: python -m pip install mypy
      
      - name: Run mypy
        run: mypy .

  lint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install linters
        run: |
          pip install black flake8

      - name: Run black
        run: black --check .

      - name: Run flake8
        run: flake8 .
